apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app: django-app
data:
  DEBUG: "True"
  SECRET_KEY: "REPLACE_ME"
  DATABASE_URL: "postgres://test_k8s:OwOtBep9Frut@192.168.31.195:5433/test_k8s"
  ALLOWED_HOSTS: "127.0.0.1,localhost"