apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app: django-app
data:
  DEBUG: "True"
  SECRET_KEY: "REPLACE_ME"
  DATABASE_URL: "postgres://test_k8s:OwOtBep9Frut@db-postgresql-0:5432/test_k8s"
  ALLOWED_HOSTS: "127.0.0.1,localhost,star-burger.test"