apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions
spec:
  schedule: "0 0 13 * 5"
  startingDeadlineSeconds: 11
  ttlSecondsAfterFinished: 20
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django-app
            image: milov52/django_app
            envFrom:
              - secretRef:
                  name: django-config
            imagePullPolicy: IfNotPresent
            command:
            - ./manage.py
            - clearsessions
          restartPolicy: OnFailure