apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    name: django-app
    component: migrations
spec:
  template:
    metadata:
      labels:
        name: django-app
        component: migrations
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: milov52/django_app
          envFrom:
            - secretRef:
                name: django-config
          imagePullPolicy: IfNotPresent
          command:
            - python
            - manage.py
            - migrate